In [1]:
import numpy as np
import pandas as pd 
df = pd.read_csv("E:\SmartStock-AI\Data\Raw\demand_forecasting_inventory_data.csv")

df.head()

,Date,Product_ID,Product,Category,Store,City,Price,Discount,Promotion,Inventory,Sales
0,2023-01-01,P001,Laptop,Electronics,S01,Pune,51664,0,0,125,6
1,2023-01-02,P001,Laptop,Electronics,S01,Pune,55837,0,0,121,4
2,2023-01-03,P001,Laptop,Electronics,S01,Pune,53257,0,0,118,3
3,2023-01-04,P001,Laptop,Electronics,S01,Pune,53285,0,0,115,3
4,2023-01-05,P001,Laptop,Electronics,S01,Pune,40087,15,1,108,7

In [2]:
# checking missing values
df.isnull().sum()

Date          0
Product_ID    0
Product       0
Category      0
Store         0
City          0
Price         0
Discount      0
Promotion     0
Inventory     0
Sales         0
dtype: int64

In [3]:
# check duplicates 
df.duplicated().sum()

np.int64(0)

In [4]:
# remove duplicates 
df = df.drop_duplicates()

In [ ]:
# handeling missing values for numerical columns 
numeric_columns = df.select_dtypes(include=np.number).columns

for col in numeric_columns:
    df[col] = df[col].fillna(df[col].median())

In [6]:
# for categorical columns 
categorical_columns = df.select_dtypes(include="object").columns

for col in categorical_columns:
    df[col] = df[col].fillna(df[col].mode()[0])

In [7]:
df["Date"] = pd.to_datetime(df["Date"])

In [ ]:
# Save cleaned dataset
import os
processed_path = r"E:\SmartStock-AI\Data\processed"
os.makedirs(processed_path, exist_ok=True)
cleaned_file = os.path.join(
    processed_path,
    "cleaned_sales_data.csv"
)
df.to_csv(cleaned_file, index=False)

print("Cleaned dataset saved successfully!")
print(cleaned_file)

Cleaned dataset saved successfully!
E:\SmartStock-AI\Data\processed\cleaned_sales_data.csv

In [11]:
# verify 
import os

print(os.path.exists(
    r"E:\SmartStock-AI\Data\processed\cleaned_sales_data.csv"
))

True

In [12]:
cleaned_df = pd.read_csv(
    r"E:\SmartStock-AI\Data\processed\cleaned_sales_data.csv"
)

print(cleaned_df.shape)
cleaned_df.head()

(159858, 11)

,Date,Product_ID,Product,Category,Store,City,Price,Discount,Promotion,Inventory,Sales
0,2023-01-01,P001,Laptop,Electronics,S01,Pune,51664,0,0,125,6
1,2023-01-02,P001,Laptop,Electronics,S01,Pune,55837,0,0,121,4
2,2023-01-03,P001,Laptop,Electronics,S01,Pune,53257,0,0,118,3
3,2023-01-04,P001,Laptop,Electronics,S01,Pune,53285,0,0,115,3
4,2023-01-05,P001,Laptop,Electronics,S01,Pune,40087,15,1,108,7